name: Test AI Agent Action
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      task-input:
        description: JSON string defining the task to execute (e.g., {"input": "Test task"})
        required: false
        default: '{}'
      task-file:
        description: Path to a JSON file containing the task definition
        required: false
      agent-name:
        description: Name of the AI agent
        required: false
        default: TestAgent
      log-level:
        description: Logging level (DEBUG, INFO, WARNING, ERROR)
        required: false
        default: INFO
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run AI Agent
        uses: ./action.yml
        with:
          task-input: '{"input": "Test task"}'
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          agent-name: TestAgent
          log-level: INFO
        id: ai-agent
      - name: Print Result
        run: echo "Result: ${{ steps.ai-agent.outputs.result }}"
