name: 'AI Agent Action'
description: 'Run an AI agent using Python'
on:
  workflow_dispatch:
    inputs:
      task-input:
        description: 'The input for the AI agent'
        required: true

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        shell: bash
        run: pip install -r requirements.txt
      - name: Run AI agent
        shell: bash
        run: python ai_agent_sdk.py --input "${{ inputs.task-input }}"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}