name: 'AI Agent Action'
on:
  workflow_dispatch:
    inputs:
      task-input:
        description: 'The input for the AI agent'
        required: true
      agent-name:
        description: 'The name of the agent'
        required: false
        default: 'default-agent'
      log-level:
        description: 'Logging level'
        required: false
        default: 'INFO'

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run AI Agent
        uses: docker://Dockerfile
        with:
          args: |
            ${{ github.event.inputs.task-input }}
            ${{ github.event.inputs.agent-name }}
            ${{ github.event.inputs.log-level }}