name: 'AI Agent Action'

on:
  workflow_dispatch:
    inputs:
      task-input:
        description: 'The input for the AI agent'
        required: true
      agent-name:
        description: 'The name of the agent'
        required: false
        default: 'default-agent'
      log-level:
        description: 'Logging level'
        required: false
        default: 'INFO'

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Run AI Agent
        run: |
          python agent_ai_sdk.py "${{ github.event.inputs.task-input }}" "${{ github.event.inputs.agent-name }}" "${{ github.event.inputs.log-level }}"
