name: 'AI Agent Action'
description: 'Run AI-powered task automation in GitHub Actions workflows'
inputs:
  task-input:
    description: 'JSON string defining the task (e.g., {"task_type": "code_summary", "input": "diff data"})'
    required: false
    default: '{}'
  task-file:
    description: 'Path to a JSON file containing the task definition'
    required: false
  openai-api-key:
    description: 'OpenAI API key for AI processing'
    required: true
  agent-name:
    description: 'Name of the AI agent'
    required: true
    default: 'AIAgent'
  log-level:
    description: 'Logging level (DEBUG, INFO, WARNING, ERROR)'
    required: false
    default: 'INFO'
outputs:
  result:
    description: 'JSON string containing the task execution result'
    value: ${{ steps.run-agent.outputs.result }}
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
    - name: Run AI Agent SDK
      id: run-agent
      run: |
        echo "result=$(python ai_agent_sdk.py)" >> $GITHUB_OUTPUT
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        AGENT_NAME: ${{ inputs.agent-name }}
        GITHUB_TOKEN: ${{ github.token }}
        AGENT_LOG_LEVEL: ${{ inputs.log-level }}
        TASK_INPUT: ${{ inputs.task-input }}
        TASK_FILE: ${{ inputs.task-file }}
        GITHUB_REPOSITORY_VISIBILITY: ${{ github.event.repository.visibility }}
