name: AI Agent Workflow
on:
  push:
    branches:
      - main
jobs:
  run-ai-agent:
    runs-on: ubuntu-latest
    env:
      AGENT_NAME: MyAIAgent
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AGENT_LOG_LEVEL: DEBUG
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv
      - name: Run AI Agent
        run: python ai_agent_sdk.py