name: AI Agent Workflow
on:
  push:
    branches:
      - main
jobs:
  run-ai-agent:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      AGENT_NAME: MyAIAgent
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AGENT_LOG_LEVEL: DEBUG
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install
          pip install python-dotenv
      - name: Run AI Agent
        run: python ai_agent_sdk.py
