name: AI Agent for Private Repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ai-agent:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Get code diff
        id: diff
        run: |
          git diff HEAD^ HEAD > diff.txt || echo "No diff available"
          echo "diff_file=diff.txt" >> $GITHUB_OUTPUT

      - name: Prepare task input
        id: prepare-task
        run: |
          DIFF_CONTENT=$(cat ${{ steps.diff.outputs.diff_file }} | jq -sR .)
          echo "task_input={\"task_type\": \"code_summary\", \"input\": $DIFF_CONTENT}" >> $GITHUB_OUTPUT

      - name: Run AI Agent Action
        id: ai-agent
        uses: ./  # Update to Algenix-Org/agent-sdk@v1 after release
        with:
          task-input: ${{ steps.prepare-task.outputs.task_input }}
          agent-name: CodeSummarizer
          log-level: DEBUG

      - name: Print Result
        run: |
          echo "Result: ${{ steps.ai-agent.outputs.result }}"
          if [ -z "${{ steps.ai-agent.outputs.result }}" ]; then
            echo "Error: No output from Action"
            exit 1
          fi

      - name: Debug failure
        if: failure()
        run: |
          env | sort
          echo "Action inputs: ${{ toJson(inputs) }}"
          echo "Action outputs: ${{ toJson(steps.ai-agent.outputs) }}"
          ls -la

      - name: Ignore certain files from triggering
        run: |
          echo "::add-mask::ai-agent-action.yml"
          echo "::add-mask::Dockerfile"
          echo "::add-mask::.github/actions"
