name: Publish AI Agent Action

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Verify Action files
        run: |
          test -f ai-agent-action.yml || (echo "Error: ai-agent-action.yml missing" && exit 1)
          test -f ai_agent_sdk.py || (echo "Error: ai_agent_sdk.py missing" && exit 1)
          test -f requirements.txt || (echo "Error: requirements.txt missing" && exit 1)

      - name: Announce publication
        run: |
          echo "✅ AI Agent Action verified and ready for use"
          echo "Repository: https://github.com/${{ github.repository }}"

      - name: Debug info (if fails)
        if: failure()
        run: |
          echo "🔍 Debug info:"
          git tag --list
