name: Test AI Agent Action
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run AI Agent
        uses: ./
        with:
          task-input: '{"input": "Test task"}'
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          agent-name: TestAgent
        id: ai-agent
      - name: Print Result
        run: echo "Result: ${{ steps.ai-agent.outputs.result }}"
